### ISSUE TITLE
Implement tooltips for certain articles

### ISSUE THREAD

**Issue by linnea-steward** [brad-steward/wa_css_builder#9]
```scss
a[href="/w/eddur-Adurnari/c/ajror-eri"] {
position:relative;
}

a[href="/w/eddur-Adurnari/c/ajror-eri"]:before {
    content: "a.k.a. The Elemental Plane of Air, a plane marked by nothing but various densities of atmosphere. There are not many places to stand, save on the floating villages of the aaracockra.";
    position: absolute;
    background: rgba(255,255,255, 1);
    bottom: 20px;
    left: 0;
    width: 300px;
    display: none;
    padding: 10px;
}

a[href="/w/eddur-Adurnari/c/ajror-eri"]:hover:before {
display: block;
}
```
